import Head from 'next/head';
import { useQuery } from 'urql';
import Product from '../components/Product';
import { PRODUCT_QUERY } from '../lib/query';
import { Gallary } from '../styles/Gallary';

export default function Home() {
	// fetch products from strapi
	const [results] = useQuery({ query: PRODUCT_QUERY });
	const { data, fetching, error } = results;

	if (fetching) {
		return <p>Loading...</p>;
	}
	if (error) {
		return <p>Error: {error.message}</p>;
	}
	const products = data.products.data;

	console.log(products);

	return (
		<div>
			<Head>
				<title>Bazar-Soday</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<h1>Welcome to Bazar-soday</h1>
				<Gallary>
					{products.map((product) => (
						<Product
							key={product.attributes.slug}
							product={product}
						/>
					))}
				</Gallary>
			</main>
		</div>
	);
}
